Repository bradmasy/LENZ-ANDROID, pull requests merged in 2023-10, with the labels that each got.

#2 3
  .gitignore
  assets/images/homepage_bg.jpg
  lib/auth/auth_routes.dart
  lib/auth/domain/app_user.dart
  lib/auth/domain/constants.dart
  lib/auth/domain/dtos/login_dto.dart
  lib/auth/domain/dtos/signup_dto.dart
  lib/auth/get_it_setup.dart
  lib/auth/services/auth_service.dart
  lib/auth/services/auth_service_api.dart
  lib/auth/view/login.dart
  lib/auth/view/signup.dart
  lib/globals.dart
  lib/homepage.dart
  lib/main.dart
  lib/routes.dart
  lib/this_is_a_test.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#11 Develop
  lib/auth/domain/app_user.dart
  lib/auth/domain/constants.dart
  lib/auth/get_it_setup.dart
  lib/auth/services/auth_service_api.dart
  lib/auth/view/login.dart
  lib/auth/view/signup.dart
  lib/dash_page.dart
  lib/globals.dart
  lib/homepage.dart
  lib/main.dart
  lib/routes.dart
  lib/this_is_a_test.dart
Labels: duplicate, enhancement

#22 19
  lib/HttpApi/HttpApi.dart
  lib/HttpApi/HttpApiService.dart
  lib/components/AlbumTile1.dart
  lib/components/PhotoTile.dart
  lib/pages/AddAlbum.dart
  lib/pages/AddAlbumPhoto.dart
  lib/pages/AlbumPhotos.dart
  lib/pages/Albums.dart
  lib/pages/AllPhotos.dart
  lib/pages/Dashboard.dart
Labels: enhancement

#23 20 add a search page
  lib/HttpApi/HttpApi.dart
  lib/HttpApi/HttpApiService.dart
  lib/pages/AllPhotos.dart
  lib/pages/Dashboard.dart
  lib/pages/Search.dart
Labels: enhancement

#25 #24 add home page with logout button
  lib/HttpApi/HttpApi.dart
  lib/auth/services/AuthServiceApi.dart
  lib/auth/view/Login.dart
  lib/components/PhotoTileLarge.dart
  lib/pages/AddPhoto.dart
  lib/pages/Dashboard.dart
  lib/pages/Home.dart
  lib/routes.dart
Labels: enhancement

#26 #20 fix time search bug
  lib/HttpApi/HttpApi.dart
  lib/pages/Search.dart
Labels: bug
